version: '2.1'

services:
  discovery:
    command: -server -bootstrap -advertise 192.168.99.100
    image: progrium/consul:latest
    hostname: 127.0.0.1.xip.io
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"

  portafolio_api:
    image: test/portafolio
    ports:
      - "57116:57116"
    environment:
      CONSUL_HOST: discovery
      DISCOVERY_ENABLED: "true"
    depends_on:
      - discovery
    links:
      - discovery
  pricing_api:
    image: test/pricing

    ports:
      - "57216:57216"
    environment:
      CONSUL_HOST: discovery
      DISCOVERY_ENABLED: "true"
    depends_on:
      - discovery
      - portafolio_api
    links:
      - discovery
      - portafolio_api
