version: '3.3'

services:
  mongo:
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    environment:
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test
      - MONGODB_DATABASE=test
  spring-boot-microservices-docker:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    image: spring-boot-microservices-docker
    links:
      - mongo
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test
      - MONGODB_DATABASE=test

    depends_on:
      - mongo
    ports:
      - "5005:5005"
      - "8080:8080"
